"use client";
import { useEffect, useMemo, useState } from "react";
type Msg={role:"user"|"assistant";content:string}; type Audit={at:string;event:string};
export default function Home(){
 const[messages,setMessages]=useState<Msg[]>([]);const[input,setInput]=useState("");const[busy,setBusy]=useState(false);const[audit,setAudit]=useState<Audit[]>([]);
 useEffect(()=>{try{const m=localStorage.getItem("jipity_messages"),a=localStorage.getItem("jipity_audit");if(m)setMessages(JSON.parse(m));if(a)setAudit(JSON.parse(a));}catch{}},[]);
 useEffect(()=>{localStorage.setItem("jipity_messages",JSON.stringify(messages.slice(-40)));},[messages]);
 useEffect(()=>{localStorage.setItem("jipity_audit",JSON.stringify(audit.slice(-100)));},[audit]);
 const status=useMemo(()=>busy?"thinking":"ready",[busy]);
 async function send(){const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user" as const,content:text}];setMessages(next);setInput("");setBusy(true);setAudit(a=>[...a,{at:new Date().toISOString(),event:"User message sent to private Jipity chat endpoint"}]);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next.slice(-20)})});const data=await r.json();if(!r.ok)throw new Error(data?.error||"Request failed");setMessages(m=>[...m,{role:"assistant",content:data.text}]);setAudit(a=>[...a,{at:new Date().toISOString(),event:"Jipity response received"}]);}catch(e:any){setMessages(m=>[...m,{role:"assistant",content:`Connection error: ${e.message}`}]);}finally{setBusy(false);}}
 function clearLocal(){setMessages([]);setAudit([]);localStorage.removeItem("jipity_messages");localStorage.removeItem("jipity_audit");}
 return <main className="shell"><div className="top"><div><div className="brand">Jipity ✦</div><div className="sub">Private companion · evidence before certainty</div></div><span className="pill">{status}</span></div><div className="card"><div className="chat">{messages.length===0&&<div className="assistant msg">Hi. I’m Jipity. Ask me something enormous, strange, practical, or completely ordinary.</div>}{messages.map((m,i)=><div key={i} className={`msg ${m.role}`}>{m.content}</div>)}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} placeholder="Talk to Jipity…"/><button onClick={send} disabled={busy}>Send</button></div><div className="notice">V1 stores chat history only in this browser. No external posting or autonomous actions are enabled.</div><details className="panel"><summary>Safety & activity</summary><div className="row" style={{margin:"10px 0"}}><span className="pill">No spending</span><span className="pill">No impersonation</span><span className="pill">No external data sharing</span><span className="pill">External actions disabled</span></div><button className="smallbtn" onClick={clearLocal}>Clear local memory & log</button><div className="audit">{audit.slice().reverse().map((x,i)=><div key={i}>{x.at}: {x.event}</div>)}</div></details></div></main>;
}
